name: Check Labels
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

  workflow_dispatch:

jobs:
  devnet-pass:
    name: devnet-pass
    runs-on: ubuntu-latest
    steps:
      - name: Check for Required Label
        if: ${{ contains(fromJson('["devnet-pass"]'), github.event.label.name) != true }}
        run: |
          echo "Error: Required label 'devnet-pass' is missing."
          exit 1
  testnet-pass:
    name: testnet-pass
    runs-on: ubuntu-latest
    steps:
      - name: Check for Required Label
        if: ${{ contains(fromJson('["testnet-pass"]'), github.event.label.name) != true }}
        run: |
          echo "Error: Required label 'testnet-pass' is missing."
          exit 1
