name: Label-based Triggers
on:
  pull_request:
    types:
      - labeled

jobs:
  comment_on_breaking_change:
    runs-on: ubuntu-latest
    steps:
      - name: Check if 'breaking change' label is added
        if: github.event.label.name == 'breaking-change'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@opentensor/cerebrum breaking change detected! Please review the changes
              and prepare accordingly!'
            })
